namespace citysetSprites {
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub101 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub102 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub103 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub104 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub107 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub108 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub109 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub110 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub111 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub112 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub201 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub202 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub203 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub204 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub207 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub208 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub209 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub210 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub211 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub212 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub301 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub302 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub303 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub307 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub308 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub309 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub310 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub311 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub312 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub401 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub402 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub403 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub404 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub407 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub408 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub409 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub410 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub411 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub412 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub501 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub502 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub503 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub504 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub507 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub508 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub509 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub510 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub511 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitybub512 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat09 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitycat18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcityman8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitynurse17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const gcitypolice09 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item09 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const item57 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ice = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const train = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const citybg = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const citybg2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gcityhospital = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gcityhospital2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gapart = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gapart2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const house1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const house2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gburgrshop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gburgrshop2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gcafe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gcafe2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gsushibilding = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const nyansushi = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const nyansushi2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gconvenience = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gconvenience2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gstation = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const park = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const gcity2 = image.ofBuffer(hex``);

}
